planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05
  KPIECEkConfigDefault:
    type: geometric::KPIECE1
    range: 0.0
    goal_bias: 0.05
    border_fraction: 0.9
    failed_expansion_score_factor: 0.5
    min_valid_path_fraction: 0.5

arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
