#!/usr/bin/env bash
# SO-ARM laptop camera: USB capture -> x264enc -> MediaMTX on TCP 8889.
# DEVICE defaults to /dev/video2 and that node must be USB2.0_CAM1.
# SO_ARM_CAMERA_PARSE_ONLY=1 prints the device and exits before MediaMTX.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

DEFAULT_DEVICE="/dev/video2"
DEVICE="${DEVICE:-${DEFAULT_DEVICE}}"
export DEVICE
SYSFS="${SO_ARM_VIDEO_SYSFS:-/sys/class/video4linux}"

if [[ "${SO_ARM_CAMERA_FORBID_START:-}" == "1" && "${SO_ARM_CAMERA_PARSE_ONLY:-}" != "1" ]]; then
  echo "ERROR: camera start blocked" >&2
  exit 99
fi

node="$(basename -- "${DEVICE}")"
name_file="${SYSFS}/${node}/name"
if [[ -f "${name_file}" ]]; then
  name="$(tr -d '\r\n' < "${name_file}")"
else
  name=""
fi

node_exists() {
  if [[ -n "${SO_ARM_VIDEO_SYSFS:-}" ]]; then
    [[ -e "${SYSFS}/${node}" ]]
    return
  fi
  [[ -e "${DEVICE}" ]]
}

if [[ "${DEVICE}" == "${DEFAULT_DEVICE}" ]]; then
  if [[ "${name}" != *USB2.0_CAM1* ]]; then
    echo "ERROR: ${DEVICE} is not USB2.0_CAM1 (sysfs '${name:-missing}'); refusing (integrated camera is /dev/video0)" >&2
    exit 2
  fi
else
  if ! node_exists; then
    echo "ERROR: ${DEVICE} does not exist" >&2
    exit 2
  fi
  if [[ "${name,,}" == *metadata* ]]; then
    echo "ERROR: ${DEVICE} is metadata ('${name}'); refusing" >&2
    exit 2
  fi
fi

echo "SO-ARM camera ${DEVICE} name ${name}"
if [[ "${SO_ARM_CAMERA_PARSE_ONLY:-}" == "1" ]]; then
  exit 0
fi
if [[ "${SO_ARM_CAMERA_FORBID_START:-}" == "1" ]]; then
  echo "ERROR: camera start blocked" >&2
  exit 99
fi

mkdir -p "${ROOT}/logs" "${ROOT}/run"
if [[ -f "${ROOT}/run/mediamtx.pid" ]] && kill -0 "$(cat "${ROOT}/run/mediamtx.pid")" 2>/dev/null; then
  echo "already running (pid $(cat "${ROOT}/run/mediamtx.pid")). ${ROOT}/stop.sh first." >&2
  exit 1
fi

extra_hosts="[]"
if command -v tailscale >/dev/null 2>&1; then
  ip="$(tailscale ip -4 2>/dev/null | head -n 1 | tr -d '[:space:]' || true)"
  if [[ "${ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    extra_hosts="[\"${ip}\"]"
  fi
fi

cat > "${ROOT}/run/mediamtx.yml" <<EOF
# Generated by video/so-arm/start.sh. WebRTC on TCP 8889, RTP from 127.0.0.1:5004.
logLevel: info
logDestinations: [file]
logFile: ${ROOT}/logs/mediamtx.log
udpMaxPayloadSize: 1200

rtsp: true
rtmp: false
hls: false
srt: false
moq: false
api: false
metrics: false
pprof: false
playback: false

webrtc: true
webrtcAddress: :8889
rtspAddress: :8554
webrtcEncryption: false
webrtcAllowOrigins: ["*"]
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: ""
webrtcIPsFromInterfaces: true
webrtcIPsFromInterfacesList: [tailscale0]
webrtcAdditionalHosts: ${extra_hosts}
webrtcICEServers2: []

paths:
  cam:
    source: udp+rtp://127.0.0.1:5004
    rtpSDP: |
      v=0
      o=- 0 0 IN IP4 127.0.0.1
      s=cam
      c=IN IP4 127.0.0.1
      t=0 0
      m=video 5004 RTP/AVP 96
      a=rtpmap:96 H264/90000
      a=fmtp:96 packetization-mode=1
EOF

if [[ -n "${SO_ARM_MEDIAMTX_BIN:-}" ]]; then
  mediamtx_bin="${SO_ARM_MEDIAMTX_BIN}"
elif [[ -x "${ROOT}/bin/mediamtx" ]]; then
  mediamtx_bin="${ROOT}/bin/mediamtx"
elif [[ -x "${ROOT}/../bin/mediamtx" ]]; then
  mediamtx_bin="${ROOT}/../bin/mediamtx"
else
  echo "missing mediamtx binary (video/so-arm/bin/mediamtx or video/bin/mediamtx)" >&2
  exit 1
fi

: > "${ROOT}/logs/mediamtx.log"
: > "${ROOT}/logs/gst.log"
nohup "${mediamtx_bin}" "${ROOT}/run/mediamtx.yml" >> "${ROOT}/logs/mediamtx.log" 2>&1 &
echo $! > "${ROOT}/run/mediamtx.pid"
nohup "${ROOT}/gst-publish.sh" >> "${ROOT}/logs/gst.log" 2>&1 &
echo $! > "${ROOT}/run/gst.pid"
disown || true

echo "SO-ARM camera publishing ${DEVICE} -> RTP 127.0.0.1:5004"
echo "  page: TCP 8889 /cam/"
echo "stop with: ${ROOT}/stop.sh"
